export type Language = "ko" | "ja";

export const content = {
  ko: {
    languageName: "한국어",
    eyebrow: "THE WEDDING OF",
    scroll: "SCROLL TO BEGIN",
    musicPlay: "배경 음악 재생",
    musicPause: "배경 음악 일시정지",
    musicOn: "MUSIC ON",
    musicOff: "MUSIC OFF",
    musicLoading: "LOADING",
    musicError: "음악을 재생할 수 없습니다.",
    ourWedding: "OUR WEDDING",
    introTitle: "서로의 계절이 만나\n하나의 이야기가 되었습니다",
    introBody: "오래도록 함께 웃고, 서로의 곁을 지키며\n이제 같은 방향으로 걸어가려 합니다.\n소중한 분들을 모시고 첫걸음을 내딛는 날,\n따뜻한 마음으로 함께해 주시면 감사하겠습니다.",
    storyQuote: "In every season, with you.",
    storyCaption: "서로에게 가장 따뜻한 풍경이 되어",
    together: "TOGETHER, ALWAYS",
    couple: "두 사람",
    groom: "신랑",
    bride: "신부",
    dateEyebrow: "SAVE THE DATE",
    dateTitle: "우리의 가장 빛나는 날",
    weekday: "일요일",
    time: "오후 1시",
    dayUnit: "일",
    weddingDay: "D-DAY",
    countBefore: "D -",
    countAfter: "D +",
    dateFoot: "함께해 주실 그날을 기다립니다",
    galleryEyebrow: "MOMENTS OF US",
    galleryTitle: "Gallery",
    galleryDesc: "함께 쌓아온 아름다운 순간들",
    photo: "PHOTO",
    enlarge: "확대",
    close: "닫기",
    previous: "이전 사진",
    next: "다음 사진",
    invitationEyebrow: "WITH ALL OUR LOVE",
    invitationTitle: "초대합니다",
    invitationBody: "새로운 시작을 앞둔 저희 두 사람에게\n여러분의 축복은 오래도록 간직할 선물이 됩니다.\n그날, 기쁜 마음으로 뵙겠습니다.",
    venueEyebrow: "THE CELEBRATION",
    venueTitle: "오시는 길",
    venueNote: "정확한 주소와 교통 안내는 확정 후 이곳에 추가됩니다.",
    mapNote: "지도 버튼은 위치 확정 후 연결됩니다.",
    mapKakao: "카카오맵",
    mapNaver: "네이버지도",
    mapTmap: "TMAP",
    contactEyebrow: "GET IN TOUCH",
    contactTitle: "연락처",
    contactNote: "연락처가 등록되면 전화 버튼이 표시됩니다.",
    father: "아버지",
    mother: "어머니",
    call: "전화하기",
    accountEyebrow: "SEND YOUR HEART",
    accountTitle: "마음 전하실 곳",
    accountNote: "멀리서 마음을 전하고 싶으신 분들을 위해 준비한 공간입니다.",
    groomSide: "신랑측 마음 전하실 곳",
    brideSide: "신부측 마음 전하실 곳",
    accountPending: "계좌 정보가 준비되면 이곳에 표시됩니다.",
    copyAccount: "계좌번호 복사",
    copyLink: "링크 복사",
    copied: "복사되었습니다",
    shareEyebrow: "SHARE OUR DAY",
    shareTitle: "함께 나누어 주세요",
    shareBody: "저희의 소중한 날을 함께 기억해 주세요.",
    kakaoShare: "카카오톡 공유",
    kakaoPending: "카카오톡 공유 설정 전입니다. 링크 복사를 이용해 주세요.",
    copyFailed: "복사에 실패했습니다. 주소창에서 링크를 복사해 주세요.",
    ending: "저희의 새로운 시작을\n함께 축복해 주셔서 감사합니다.",
    endingEnglish: "Thank you for being part of our story.",
  },
  ja: {
    languageName: "日本語",
    eyebrow: "THE WEDDING OF",
    scroll: "SCROLL TO BEGIN",
    musicPlay: "BGMを再生",
    musicPause: "BGMを一時停止",
    musicOn: "MUSIC ON",
    musicOff: "MUSIC OFF",
    musicLoading: "LOADING",
    musicError: "音楽を再生できませんでした。",
    ourWedding: "OUR WEDDING",
    introTitle: "ふたりの季節が重なり\nひとつの物語に",
    introBody: "このたび 私たちは結婚することとなりました。\nこれまで支えてくださった皆さまへの感謝を胸に\n新たな一歩を踏み出します。\nぜひ私たちの門出を見守っていただけましたら幸いです。",
    storyQuote: "In every season, with you.",
    storyCaption: "どんな季節も あなたとともに",
    together: "TOGETHER, ALWAYS",
    couple: "ふたりのこと",
    groom: "新郎",
    bride: "新婦",
    dateEyebrow: "SAVE THE DATE",
    dateTitle: "私たちの大切な日",
    weekday: "日曜日",
    time: "午後1時",
    dayUnit: "日",
    weddingDay: "D-DAY",
    countBefore: "D -",
    countAfter: "D +",
    dateFoot: "皆さまにお会いできる日を楽しみにしています",
    galleryEyebrow: "MOMENTS OF US",
    galleryTitle: "Gallery",
    galleryDesc: "ふたりで重ねてきた大切な瞬間",
    photo: "PHOTO",
    enlarge: "拡大",
    close: "閉じる",
    previous: "前の写真",
    next: "次の写真",
    invitationEyebrow: "WITH ALL OUR LOVE",
    invitationTitle: "ご招待",
    invitationBody: "ご多用中とは存じますが\n私たちの新たな門出にお立ち会いいただけましたら\nこの上ない喜びです。\n当日 お会いできますことを心より楽しみにしております。",
    venueEyebrow: "THE CELEBRATION",
    venueTitle: "会場のご案内",
    venueNote: "会場の詳しい住所とアクセス方法は 確定次第こちらでご案内いたします。",
    mapNote: "地図のリンクは詳細が決まり次第公開します。",
    mapKakao: "Kakao Map",
    mapNaver: "NAVER Map",
    mapTmap: "TMAP",
    contactEyebrow: "GET IN TOUCH",
    contactTitle: "ご連絡先",
    contactNote: "電話番号が登録されると 通話ボタンが表示されます。",
    father: "父",
    mother: "母",
    call: "電話をかける",
    accountEyebrow: "SEND YOUR HEART",
    accountTitle: "お気持ちをお寄せいただく方へ",
    accountNote: "遠方からお祝いのお気持ちを届けてくださる方のためにご用意しています。",
    groomSide: "新郎側",
    brideSide: "新婦側",
    accountPending: "口座情報は準備が整い次第 ご案内いたします。",
    copyAccount: "口座番号をコピー",
    copyLink: "リンクをコピー",
    copied: "コピーしました",
    shareEyebrow: "SHARE OUR DAY",
    shareTitle: "大切な一日を",
    shareBody: "私たちの特別な日を 一緒に覚えていただけたら嬉しいです。",
    kakaoShare: "KakaoTalkで共有",
    kakaoPending: "KakaoTalkの共有は準備中です。リンクのコピーをご利用ください。",
    copyFailed: "コピーできませんでした。アドレスバーからリンクをコピーしてください。",
    ending: "私たちの新しい門出を\n温かく見守ってくださり\nありがとうございます。",
    endingEnglish: "Thank you for being part of our story.",
  },
} as const;

export type WeddingCopy = typeof content[Language];
