export type Language = "ko" | "ja";

export const content = {
  ko: {
    languageName: "한국어",
    eyebrow: "THE WEDDING OF",
    coverScript: "Our wedding day",
    coverKicker: "DONGGYUN & TSUKINA",
    scroll: "INVITATION",
    musicPlay: "배경 음악 재생",
    musicPause: "배경 음악 일시정지",
    musicOn: "MUSIC ON",
    musicOff: "MUSIC OFF",
    musicLoading: "LOADING",
    musicError: "음악을 재생할 수 없습니다.",
    ourWedding: "OUR WEDDING",
    introTitle: "결혼합니다.",
    introBody: "두 사람이 사랑으로 만나\n진실과 이해로써 하나를 이루려 합니다.\n이 두 사람을 지성으로 아끼고 돌봐주신\n여러 어른과 친지를 모시고 서약을 맺고자 하오니\n바쁘신 가운데 두 사람의 앞날을\n가까이에서 축복해 주시면 고맙겠습니다.",
    storyQuote: "Together, from this day.",
    storyCaption: "서로의 가장 다정한 오늘이 되어",
    together: "TOGETHER, ALWAYS",
    couple: "두 사람",
    groom: "신랑",
    bride: "신부",
    dateEyebrow: "SAVE THE DATE",
    dateTitle: "우리의 가장 빛나는 날",
    weekday: "일요일",
    time: "낮 12시",
    dayUnit: "일",
    weddingDay: "D-DAY",
    countBefore: "D -",
    countAfter: "D +",
    dateFoot: "함께해 주실 그날을 기다립니다",
    galleryEyebrow: "MOMENTS OF US",
    galleryTitle: "Gallery",
    galleryDesc: "함께 쌓아온 아름다운 순간들",
    photo: "PHOTO",
    enlarge: "확대",
    close: "닫기",
    previous: "이전 사진",
    next: "다음 사진",
    invitationEyebrow: "WITH ALL OUR LOVE",
    invitationTitle: "소중한 분들을 초대합니다",
    invitationBody: "두 사람의 첫걸음을\n따뜻한 마음으로 함께해 주세요.",
    venueEyebrow: "THE CELEBRATION",
    venueTitle: "오시는 길",
    venueNote: "스탠포드호텔서울 2층 그랜드볼룸홀",
    mapNote: "지도를 눌러 자세한 위치를 확인하실 수 있습니다.",
    mapKakao: "카카오맵",
    mapNaver: "네이버지도",
    mapTmap: "TMAP",
    contactEyebrow: "GET IN TOUCH",
    contactTitle: "연락처",
    contactNote: "연락처가 등록되면 전화 버튼이 표시됩니다.",
    father: "아버지",
    mother: "어머니",
    call: "전화하기",
    accountEyebrow: "SEND YOUR HEART",
    accountTitle: "마음 전하실 곳",
    accountNote: "참석이 어려우신 분들을 위해 조심스레 안내드립니다.",
    groomSide: "신랑측 마음 전하실 곳",
    brideSide: "신부측 마음 전하실 곳",
    accountPending: "계좌 정보가 준비되면 이곳에 표시됩니다.",
    copyAccount: "계좌번호 복사",
    copyLink: "링크 복사",
    copied: "복사되었습니다",
    shareEyebrow: "SHARE OUR DAY",
    shareTitle: "함께 나누어 주세요",
    shareBody: "저희의 소중한 날을 함께 기억해 주세요.",
    kakaoShare: "카카오톡 공유",
    lineShare: "LINE 공유",
    kakaoPending: "카카오톡 공유 설정 전입니다. 링크 복사를 이용해 주세요.",
    copyFailed: "복사에 실패했습니다. 주소창에서 링크를 복사해 주세요.",
    ending: "두 사람의 새로운 시작을\n함께 축복해 주셔서 감사합니다.",
    endingEnglish: "With love, Donggyun & Tsukina.",
    endingOverline: "AND SO, OUR STORY BEGINS",
  },
  ja: {
    languageName: "日本語",
    eyebrow: "THE WEDDING OF",
    coverScript: "Our wedding day",
    coverKicker: "DONGGYUN & TSUKINA",
    scroll: "INVITATION",
    musicPlay: "BGMを再生",
    musicPause: "BGMを一時停止",
    musicOn: "MUSIC ON",
    musicOff: "MUSIC OFF",
    musicLoading: "LOADING",
    musicError: "音楽を再生できませんでした。",
    ourWedding: "OUR WEDDING",
    introTitle: "結婚いたします。",
    introBody: "私たちは愛によって出会い\n真心と理解をもって ひとつの家庭を築くこととなりました。\n今日まで大切に見守り育ててくださった\n皆さまをお招きし 誓いを結びたいと存じます。\nご多用のところ恐縮ではございますが\nふたりの門出をお見守りいただけましたら幸いです。",
    storyQuote: "Together, from this day.",
    storyCaption: "お互いのいちばん優しい今日になって",
    together: "TOGETHER, ALWAYS",
    couple: "ふたりのこと",
    groom: "新郎",
    bride: "新婦",
    dateEyebrow: "SAVE THE DATE",
    dateTitle: "私たちの大切な日",
    weekday: "日曜日",
    time: "正午12時",
    dayUnit: "日",
    weddingDay: "D-DAY",
    countBefore: "D -",
    countAfter: "D +",
    dateFoot: "皆さまにお会いできる日を楽しみにしています",
    galleryEyebrow: "MOMENTS OF US",
    galleryTitle: "Gallery",
    galleryDesc: "ふたりで重ねてきた大切な瞬間",
    photo: "PHOTO",
    enlarge: "拡大",
    close: "閉じる",
    previous: "前の写真",
    next: "次の写真",
    invitationEyebrow: "WITH ALL OUR LOVE",
    invitationTitle: "大切な皆さまへ",
    invitationBody: "ふたりの新しい一歩を\nあたたかく見守ってください。",
    venueEyebrow: "THE CELEBRATION",
    venueTitle: "会場のご案内",
    venueNote: "スタンフォードホテルソウル 2階 グランドボールルーム",
    mapNote: "地図をタップすると詳しい位置をご確認いただけます。",
    mapKakao: "Kakao Map",
    mapNaver: "NAVER Map",
    mapTmap: "TMAP",
    contactEyebrow: "GET IN TOUCH",
    contactTitle: "ご連絡先",
    contactNote: "電話番号が登録されると 通話ボタンが表示されます。",
    father: "父",
    mother: "母",
    call: "電話をかける",
    accountEyebrow: "SEND YOUR HEART",
    accountTitle: "お気持ちをお寄せいただく方へ",
    accountNote: "ご参列が難しい方のために 謹んでご案内いたします。",
    groomSide: "新郎側",
    brideSide: "新婦側",
    accountPending: "口座情報は準備が整い次第 ご案内いたします。",
    copyAccount: "口座番号をコピー",
    copyLink: "リンクをコピー",
    copied: "コピーしました",
    shareEyebrow: "SHARE OUR DAY",
    shareTitle: "大切な一日を",
    shareBody: "私たちの特別な日を 一緒に覚えていただけたら嬉しいです。",
    kakaoShare: "KakaoTalkで共有",
    lineShare: "LINEで共有",
    kakaoPending: "KakaoTalkの共有は準備中です。リンクのコピーをご利用ください。",
    copyFailed: "コピーできませんでした。アドレスバーからリンクをコピーしてください。",
    ending: "私たちの新しい門出を\n温かく見守ってくださり\nありがとうございます。",
    endingEnglish: "With love, Donggyun & Tsukina.",
    endingOverline: "AND SO, OUR STORY BEGINS",
  },
} as const;

export type WeddingCopy = typeof content[Language];
